# Generated by Django 5.1.1 on 2025-06-18 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_customuser_bio_customuser_role'),
        ('reviews', '0002_rename_categories_category_rename_comments_comment_and_more'),
    ]

    operations = [
    ]
