# Generated by Django 5.1.1 on 2025-06-23 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_title_options'),
        ('reviews', '0004_alter_title_options_alter_userprofile_username'),
    ]

    operations = [
    ]
