# Generated by Django 5.1.1 on 2025-06-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_merge_20250617_2037'),
        ('reviews', '0004_title_rating'),
    ]

    operations = [
    ]
