# Generated by Django 5.1.1 on 2025-06-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_merge_0003_merge_20250617_2037_0004_title_rating'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='unique_review_author_title'),
        ),
    ]
